version: '3'
    
services:
  db:
    image: postgres
    environment:
      - POSTGRES_DB=${POSTGRES_DB:-postgres}
      - POSTGRES_USER=${POSTGRES_USER:-postgres}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-postgres}
      - POSTGRES_PORT=${POSTGRES_PORT:-5432}
  django-helpdesk:
    build: .
    image: django-helpdesk
    command: python3 manage.py runserver 0.0.0.0:8000
    environment:
      - DEBUG=True
      - POSTGRES_DB=${POSTGRES_DB:-postgres}
      - POSTGRES_USER=${POSTGRES_USER:-postgres}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-postgres}
      - POSTGRES_PORT=${POSTGRES_PORT:-5432}
      - DATABASE_URL=postgres://${POSTGRES_USER:-postgres}:${POSTGRES_PASSWORD:-postgres}@db:${POSTGRES_PORT:-5432}/${POSTGRES_DB:-postgres}
      - SECRET_KEY=${SECRET_KEY:-supersecretnuclearweaponskey42!}
      - DJANGO_SUPERUSER_USERNAME=${DJANGO_SUPERUSER_USERNAME:-admin}
      - DJANGO_SUPERUSER_PASSWORD=${DJANGO_SUPERUSER_PASSWORD:-admin}
    volumes:
      - .:/app
      #- django-helpdesk:/app/django_helpdesk
      - helpdesk-static:/app/static
      - helpdesk-media:/app/media
    ports:
      - "8000:8000"
    depends_on:
      - db

volumes:
  helpdesk-static:
  helpdesk-media:  