version: '3.7'
    
services:
  db:
    image: postgres
    restart: unless-stopped
    environment:
      - POSTGRES_DB=${POSTGRES_DB:-postgres}
      - POSTGRES_USER=${POSTGRES_USER:-postgres}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-postgres}
      - POSTGRES_PORT=${POSTGRES_PORT:-5432}
    networks:
      - helpdesk
    volumes:
      - helpdesk-db:/var/lib/postgresql/data

  django-helpdesk:
    restart: unless-stopped
    image: registry.gitlab.com/peter.saarland/django-helpdesk:latest
    command: "gunicorn --bind :8000 django_helpdesk.wsgi:application"
    environment:
      - DEBUG=True
      - POSTGRES_DB=${POSTGRES_DB:-postgres}
      - POSTGRES_USER=${POSTGRES_USER:-postgres}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-postgres}
      - POSTGRES_PORT=${POSTGRES_PORT:-5432}
      - DATABASE_URL=postgres://${POSTGRES_USER:-postgres}:${POSTGRES_PASSWORD:-postgres}@db:${POSTGRES_PORT:-5432}/${POSTGRES_DB:-postgres}
      - SECRET_KEY=${SECRET_KEY:-supersecretnuclearweaponskey42!}
      - DJANGO_SUPERUSER_USERNAME=${DJANGO_SUPERUSER_USERNAME:-admin}
      - DJANGO_SUPERUSER_PASSWORD=${DJANGO_SUPERUSER_PASSWORD:-admin}
    volumes:
      - helpdesk-static:/app/static
      - helpdesk-media:/app/media
    depends_on:
      - db
    networks:
      - helpdesk

  nginx:
    image: django-helpdesk-nginx
    restart: always
    volumes:
      - helpdesk-static:/static
      - helpdesk-media:/media
    labels:
      - traefik.enable=true
      - traefik.docker.network=${TRAEFIK_NETWORK:-web}
      - traefik.dh.frontend.rule=Host:${APP_DOMAINS:-django-helpdesk.127.0.0.1.xip.io}
      - traefik.dh.frontend.entryPoints=http,https
      - traefik.dh.frontend.headers.SSLRedirect=true
      - traefik.dh.port=80
    networks:
      - helpdesk
      - web

volumes:
  helpdesk-static:
  helpdesk-media:
  helpdesk-db:

networks:
  helpdesk:
  web:
    name: ${TRAEFIK_NETWORK:-web}