version: '3.7'
    
services:
  db:
    image: postgres
    restart: unless-stopped
    environment:
      - POSTGRES_DB=${POSTGRES_DB:-postgres}
      - POSTGRES_USER=${POSTGRES_USER:-postgres}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-postgres}
      - POSTGRES_PORT=${POSTGRES_PORT:-5432}
    networks:
      - helpdesk

  django-helpdesk:
    restart: unless-stopped
    image: registry.gitlab.com/peter.saarland/django-helpdesk:latest
    environment:
      - DEBUG=True
      - POSTGRES_DB=${POSTGRES_DB:-postgres}
      - POSTGRES_USER=${POSTGRES_USER:-postgres}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-postgres}
      - POSTGRES_PORT=${POSTGRES_PORT:-5432}
      - DATABASE_URL=postgres://${POSTGRES_USER:-postgres}:${POSTGRES_PASSWORD:-postgres}@db:${POSTGRES_PORT:-5432}/${POSTGRES_DB:-postgres}
      - SECRET_KEY=${SECRET_KEY:-supersecretnuclearweaponskey42!}
      - DJANGO_SUPERUSER_USERNAME=${DJANGO_SUPERUSER_USERNAME:-admin}
      - DJANGO_SUPERUSER_PASSWORD=${DJANGO_SUPERUSER_PASSWORD:-admin}
    volumes:
      #- .:/app
      - helpdesk-static:/app/static
      - helpdesk-media:/app/media
    ports:
      - "8000:8000"
    depends_on:
      - db
    networks:
      - helpdesk


volumes:
  helpdesk-static:
  helpdesk-media:  

networks:
  helpdesk: